# This single codebase performs generating of subject, verb, article, adjective, and noun.
# True microservices would have separate codebases, but for our purposes a single codebase is fine.

---
# Items that apply to ALL profiles:
# Now we moved all eureka config details configuration server, hence commenting below code and adding config server properties
#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://localhost:8010/eureka/
      #defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

# Now we moved all profile with words to git config repo so that configuration server can provide the details, hence commenting below code and adding config server properties application.yml

#---
## Now we have moved sentence webservice to a different project in commons so commenting below lines
#spring:
#  profiles: sentence
#server:
#  port: 8020
## This a fix or hack for clubing all word and sentence rest services into one project. As word controller throws error for words property
#words: NotApplicable
    
#---
#spring:
#  profiles: subject
#words: I,You,He,She,It
#  
#---
#spring:
#  profiles: verb
#words: ran,knew,had,saw,bought
#
#---
#spring:
#  profiles: article
#words: a,the
#
#---
#spring:
#  profiles: adjective
#words: reasonable,leaky,suspicious,ordinary,unlikely
#
#---
#spring:
#  profiles: noun
#words: boat,book,vote,seat,backpack,partition,groundhog

# Note: all properties defined in this file are subject to replacement by the configuration server.
---
words: fallback
