---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/konduruvijaykumar/spring-cloud-boot-lab
          searchPaths: configdata
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001


# Not Working, this should work if this was directly a git repo intead of project inside spring-cloud-boot-lab repo, getting error in console unable clone
# example: https://github.com/konduruvijaykumar/configdata -- where configdata itself is a git repo
# https://github.com/konduruvijaykumar/spring-cloud-boot-lab/tree/master/configdata
# spring.cloud.config.server.git.uri = "https://github.com/konduruvijaykumar/spring-cloud-boot-lab/configdata"