---
# Allow thymeleaf template changes to reload:
spring.thymeleaf.cache: false

# Zuul-proxied services can be found by calling /services/subject, /services/verb, etc.
zuul:
  prefix: /services
  #prefix: /api   # Then we call /api/subject, /api/verb, etc.
